brew:
  enable_update: false
  enable_upgrade: false
  add_repositories:
    - homebrew/dupes
    - homebrew/versions
    - homebrew/binary
    - peco/peco
    - motemen/ghq
  install_packages:
    - brew-cask
    - coreutils
    - findutils
    - zsh
    - bash
    - vim
    - tmux
    - git
    - hub
    - tig
    - ghq
    - imagemagick
    - wget
    - rsync
    - curl
    - tree
    - openssl
    - libyaml
    - readline
    - markdown
    - jq
    - peco
    - ctags
    - rbenv
    - ruby-build
    - mysql
    - postgresql
    - node
    - redis
    - heroku-toolbelt
  install_apps:
    - atom
    - alfred
    - google-chrome
    - iterm2
    - skype
    - macvim
    - anvil
    - sequel-pro
    - cyberduck
    - sourcetree
    - gyazo
    - slack
    - virtualbox
    - google-japanese-ime
    - dash
    - dropbox
    - xtrafinder
    - appcleaner
    - caffeine
